## code to prepare `abgov_qaqc_flags` dataset goes here
# See: https://training.energy.gov.ab.ca/Forms/PR_Reference_Tables.xlsx
#   (found on https://www.alberta.ca/information-for-air-data-users)
abgov_qaqc_flags <- data.frame(
  flag = c(
    "A",
    "AM",
    "C",
    "D",
    "DUP",
    "EC",
    "FB",
    "FI",
    "G",
    "GT",
    "H",
    "K",
    "L",
    "LT",
    "M",
    "M2",
    "MB",
    "MS",
    "N",
    "NRM",
    "O",
    "O2",
    "O4",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "UI",
    "V",
    "V10",
    "V4",
    "V5",
    "V6",
    "V7",
    "V9",
    "X",
    "Y",
    "Z"
  ),
  flag_name = c(
    "Act of Nature",
    "Additional Monitoring",
    "Calibration",
    "Dry Sample",
    "Duplicate Data",
    "Equipment Change",
    "Field Blank",
    "Failed Investigation",
    "Out For Repair",
    "Over Range",
    "Historical Data",
    "Collection Error",
    "Local Interference",
    "Below MDL/MRV",
    "Missing Data",
    "QA/QC tests failed",
    "Method Blank",
    "Missing Sample",
    "Not In Service",
    "Non Routine Maintenance",
    "Operator Error",
    "Exceeded sample duration",
    "Less than sample duration",
    "Power Failure",
    "Quality Assurance",
    "Recovery",
    "Daily Zero Span",
    "Exceeds Temperature Limits",
    "Under Investigation",
    "Valid Data",
    "Valid but insufficient data for QA/QC",
    "Valid but does not meet QC",
    "Contamination Present",
    "Valid but qualified due to non-standard sampling conditions",
    "Below MDL/MRV but replaced with MDL/MRV",
    "Insufficient sample volume",
    "Equipment Malfunction",
    "Routine Maintenance",
    "Vandalism"
  ),
  flag_description = c(
    "Reported data is subject to influences of act of nature events (e.g. wildfire smoke). Detailed reasoning should be provided in the comment.",
    "Reported data is submitted by industry but not required as part of their approval.",
    "The time period when a three point calibration is performed. This is expected monthly as per AMD requirements (AMD Chapter 7: Calibration, Cal 2-G). Use whenever a calibration is conducted, with a value (when 75% of the hour is met) or without a value (if 75% of the hour is not met)",
    "Dry sample collected (i.e. no precipitation occurred)",
    "Second sample or reading with same station and VVC",
    "A flag that must be used whenever a change is made to an instrument that might affect the data. This flag should be used once for an instrument change and should be used in a time period after the last reading from the previous configuration and before or on the first reading from the new configuration. Eg. Changing a piece of equipment for another of the same make and model Eg2. Changing the internals of an instrument.",
    "Used for lab analysis only. This is when analysis is run on a sample placed in the field but intentionally not used to collect data (left sealed) in order to determine the effect field placement and transport had on a result that should be zero.",
    "Reported data was investigated and found to be inaccurate. This flag can only be assigned by internal database Administrators.",
    "Instrumentation is down to be repaired or replaced.",
    "Reported data is at or above accurate equipment operating range.",
    "Reported data that cannot be validated against current practices. Unknown effects imposed on the reported data. This flag can only be assigned by internal database administrators",
    "Identifies non-human caused collection errors (e.g. data logger error or communication error). Detailed reasoning should be provided in the comment.",
    "Reported data is subject to local interference caused by activity in the local area and not under the control of the station operator or facility owner (e.g construction near station). Data may not be regionally representative. Unknown effects imposed on the reported data.",
    "Reported data is below accurate detection/identification limit of instrument/analysis method",
    "Used for migrated data that was missing. This flag can only be assigned by internal database administrators",
    "Reported data failed the data quality control checks. This flag only applies to reported data subject to data quality control checks as outlined by the Air Monitoring Directive.",
    "Used for lab analysis only. This is when analysis is run on a sample that was not placed in the field and intentionally not used to collect data (left sealed) in order to verify the lab analysis method.",
    "Used for samples that were lost. Detailed reasoning should be provided in the comment.",
    "Analyzer not currently running (Pre-startup or post-shutdown) long Term",
    "Unexpected maintenance performed on equipment (usually due to a malfunction).",
    "A broad class of issues (calibration error, wrong setup, span issue, communication setup, etc.). Detailed reasoning should be provided in the comment. Unknown effects imposed on the reported data.",
    "Reported data was from a sample that was collected over a time frame exceeding the prescribed sampling duration.",
    "Reported data was from a sample that was collected over a time frame less than the prescribed sampling duration.",
    "Power failure at the station.",
    "Instrument is being audited.",
    "Used for warmup/stabilization after power failure or new installation.",
    "The time period when a zero-span performed. This is expected daily as per AMD requirements (AMD Chapter 7: Calibration, Cal 4-A). Use whenever a zero/span is conducted, with a value (when 75% of the hour is met) or without a value (if 75% of the hour is not met).",
    "Station temperature is too high/low for instrument operation/accuracy.",
    "Reported data is suspected of having accuracy issues and is being investigated. This flag can only be assigned by internal database Administrators.",
    "Reported data was 'questioned' and found valid. No flag is used for normal valid data",
    "Reported data did not go through all quality control checks due to insufficient data collected. This flag only applies to reported data subject to data quality control checks as outlined by the Air Monitoring Directive.",
    "Reported data only partially meeting the data quality control checks. This flag only applies to reported data subject to data quality control checks as outlined by the Air Monitoring Directive.",
    "Reported data is subject to the influence of contamination present. Unknown effects imposed on the reported data.",
    "Reported data is in non-standard sampling conditions. This flag only applies to reported data subject to data quality control checks as outlined by the Air Monitoring Directive.",
    "Collected data is below accurate analysis method detection limits or equipment operating limits, so the reported data is replaced with the method detection limit or equipment operational limit.",
    "Insufficient sample collected. This flag only applies to precipitation collection type. Unknown effects imposed on the reported data.",
    "A general flag that identifies the malfunction of equipment. Detail reasoning must be provided in the comment. Unknown effects imposed on the reported data.",
    "Preventative maintenance routinely carried out on an equipment (as per the AMD, instrumentation manual, and QAP documentation) to ensure proper operation.",
    "Equipment not operating properly due to externally caused damage"
  )
)

usethis::use_data(abgov_qaqc_flags, overwrite = TRUE)
